
version: "3.8"

services:

#  # MongoDB for Groups
  mongodb-group:
    image: mongo:latest
    container_name: mongodb-group
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /host_mnt/c/Users/Sahar/WebstormProjects/group-service/transaction-data:/data/db
    networks:
      - digital_wallet_network

#  # Group Service
  group_service_server:
    container_name: group_service_server
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "5004:5004"
    environment:
      PORT: 5004
      MONGO_URI: mongodb://root:root@mongodb-group:27017/groupDb?authSource=admin
    depends_on:
      - mongodb-group
    volumes:
      - ./groups:/usr/src/app
    networks:
      - digital_wallet_network

networks:
  digital_wallet_network:
    driver: bridge
